import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
const canvas=document.getElementById('room'),stage=document.getElementById('stage'),card=document.getElementById('objectCard'),loader=document.getElementById('loading3d');
const scene=new THREE.Scene();scene.background=new THREE.Color(0xdce5e9);
scene.fog=new THREE.Fog(0xdce5e9,10,18);
const camera=new THREE.PerspectiveCamera(52,1,.05,100);camera.position.set(4.3,3.05,4.8);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.05,0);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=.65;controls.maxDistance=10;controls.maxPolarAngle=Math.PI/2.01;controls.screenSpacePanning=true;
const transform=new TransformControls(camera,renderer.domElement);scene.add(transform);transform.addEventListener('dragging-changed',e=>controls.enabled=!e.value);transform.addEventListener('objectChange',()=>clampSelected());transform.setTranslationSnap(.05);transform.setRotationSnap(THREE.MathUtils.degToRad(15));
scene.add(new THREE.HemisphereLight(0xffffff,0x53636a,2.7));const sun=new THREE.DirectionalLight(0xfff7e8,3.4);sun.position.set(3.2,5.5,3.8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);const fill=new THREE.PointLight(0xffffff,16,8);fill.position.set(-.8,2.2,1);scene.add(fill);
const room={w:3,d:2.4,h:2.5};let selected=null,grid=null,mode='orbit';const selectable=[];
const mats={floor:new THREE.MeshStandardMaterial({color:0xb7b4aa,roughness:.58}),wall:new THREE.MeshStandardMaterial({color:0xeeeae1,roughness:.72}),white:new THREE.MeshStandardMaterial({color:0xf7f7f5,roughness:.3}),ceramic:new THREE.MeshStandardMaterial({color:0xfdfdfc,roughness:.2}),chrome:new THREE.MeshStandardMaterial({color:0xb9c2c5,metalness:.9,roughness:.13}),wood:new THREE.MeshStandardMaterial({color:0x98704f,roughness:.46}),glass:new THREE.MeshPhysicalMaterial({color:0xd9f2f5,transparent:true,opacity:.3,roughness:.04,transmission:.55,side:THREE.DoubleSide}),dark:new THREE.MeshStandardMaterial({color:0x263238,roughness:.35}),green:new THREE.MeshStandardMaterial({color:0x56745e,roughness:.75}),water:new THREE.MeshPhysicalMaterial({color:0x9fcdd8,roughness:.08,transparent:true,opacity:.7})};
function mesh(geo,mat){const m=new THREE.Mesh(geo,mat);m.castShadow=m.receiveShadow=true;return m}function box(w,h,d,mat,x,y,z){const m=mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);scene.add(m);return m}
const floor=box(room.w,.08,room.d,mats.floor,0,-.04,0),back=box(room.w,room.h,.08,mats.wall,0,room.h/2,-room.d/2),leftWall=box(.08,room.h,room.d,mats.wall,-room.w/2,room.h/2,0);
function tileLines(){const g=new THREE.Group(),lm=new THREE.LineBasicMaterial({color:0x7d8584,transparent:true,opacity:.22});for(let x=-1.5;x<=1.5;x+=.6)g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(x,.006,-1.2),new THREE.Vector3(x,.006,1.2)]),lm));for(let z=-1.2;z<=1.2;z+=.6)g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-1.5,.007,z),new THREE.Vector3(1.5,.007,z)]),lm));scene.add(g)}tileLines();
function tag(g,type,name,brand,w,d){g.userData={type,name,brand,w,d};g.traverse(o=>{if(o.isMesh)o.userData.root=g});selectable.push(g);return g}
function toilet(x,z){const g=new THREE.Group();const pedestal=mesh(new THREE.CylinderGeometry(.2,.27,.38,32),mats.ceramic);pedestal.scale.z=.82;pedestal.position.y=.22;g.add(pedestal);const bowl=mesh(new THREE.SphereGeometry(.29,32,18,0,Math.PI*2,0,Math.PI*.62),mats.ceramic);bowl.scale.set(1,.58,1.12);bowl.position.y=.48;g.add(bowl);const seat=mesh(new THREE.TorusGeometry(.235,.035,12,32),mats.white);seat.rotation.x=Math.PI/2;seat.scale.z=1.15;seat.position.y=.55;g.add(seat);const tank=mesh(new THREE.BoxGeometry(.47,.47,.18),mats.ceramic);tank.position.set(0,.61,-.27);g.add(tank);g.position.set(x,0,z);scene.add(g);return tag(g,'toilet','Vegghengt WC','Geberit · demo',.55,.72)}
function vanity(x,z){const g=new THREE.Group();const cab=mesh(new THREE.BoxGeometry(1,.52,.47),mats.wood);cab.position.y=.5;g.add(cab);const drawer=mesh(new THREE.BoxGeometry(.92,.015,.015),mats.dark);drawer.position.set(0,.53,.245);g.add(drawer);const top=mesh(new THREE.BoxGeometry(1.04,.065,.51),mats.white);top.position.y=.795;g.add(top);const basin=mesh(new THREE.CylinderGeometry(.22,.18,.105,32),mats.ceramic);basin.scale.z=1.55;basin.position.y=.86;g.add(basin);const tap=mesh(new THREE.CylinderGeometry(.021,.021,.25,16),mats.chrome);tap.position.set(.2,1,-.12);g.add(tap);const mirror=mesh(new THREE.CircleGeometry(.39,40),new THREE.MeshStandardMaterial({color:0xa9c5cc,metalness:.42,roughness:.06}));mirror.position.set(0,1.55,-.245);g.add(mirror);g.position.set(x,0,z);scene.add(g);return tag(g,'vanity','Servantmøbel 100','Dansani · demo',1.04,.52)}
function shower(x,z){const g=new THREE.Group();const tray=mesh(new THREE.BoxGeometry(1,.045,1),mats.white);tray.position.y=.022;g.add(tray);const a=mesh(new THREE.PlaneGeometry(1,2.05),mats.glass);a.position.set(0,1.03,-.5);g.add(a);const b=mesh(new THREE.PlaneGeometry(1,2.05),mats.glass);b.rotation.y=Math.PI/2;b.position.set(-.5,1.03,0);g.add(b);const pipe=mesh(new THREE.CylinderGeometry(.017,.017,1.75,14),mats.chrome);pipe.position.set(.33,1.04,-.43);g.add(pipe);const arm=mesh(new THREE.BoxGeometry(.025,.025,.25),mats.chrome);arm.position.set(.33,1.87,-.32);g.add(arm);const head=mesh(new THREE.CylinderGeometry(.14,.14,.022,24),mats.chrome);head.position.set(.33,1.87,-.19);g.add(head);g.position.set(x,0,z);scene.add(g);return tag(g,'shower','Dusjhjørne 100 × 100','INR / Hansgrohe · demo',1,1)}
function tub(x,z){const g=new THREE.Group();const outer=mesh(new THREE.BoxGeometry(1.65,.58,.75),mats.ceramic);outer.position.y=.31;g.add(outer);const water=mesh(new THREE.BoxGeometry(1.38,.025,.53),mats.water);water.position.y=.59;g.add(water);g.position.set(x,0,z);scene.add(g);return tag(g,'tub','Frittstående badekar','VikingBad · demo',1.65,.75)}
function cabinet(x,z){const g=new THREE.Group();const c=mesh(new THREE.BoxGeometry(.45,1.75,.4),mats.wood);c.position.y=.875;g.add(c);const handle=mesh(new THREE.BoxGeometry(.02,.42,.02),mats.chrome);handle.position.set(.16,.95,.21);g.add(handle);g.position.set(x,0,z);scene.add(g);return tag(g,'cabinet','Høyskap','Fossbad · demo',.45,.4)}
function plant(x,z){const g=new THREE.Group();const pot=mesh(new THREE.CylinderGeometry(.18,.13,.32,20),mats.dark);pot.position.y=.16;g.add(pot);for(let i=0;i<8;i++){const leaf=mesh(new THREE.SphereGeometry(.13,12,8),mats.green);leaf.scale.set(.5,1.9,.42);leaf.position.set(Math.sin(i)*.12,.48+(i%3)*.08,Math.cos(i)*.1);leaf.rotation.z=(i-3.5)*.23;g.add(leaf)}g.position.set(x,0,z);scene.add(g);return tag(g,'plant','Dekorplante','Showroom',.4,.4)}
toilet(-.75,-.82);vanity(.55,-.91);shower(.98,.58);cabinet(-1.18,.32);plant(-1.12,.86);
function clampSelected(){if(!selected)return;selected.position.x=THREE.MathUtils.clamp(selected.position.x,-1.25,1.25);selected.position.z=THREE.MathUtils.clamp(selected.position.z,-.95,.95);selected.position.y=0}
function select(root){selected=root;transform.detach();if(!root){card.innerHTML='<h3>Velg et produkt</h3><p>Trykk direkte på et produkt i rommet for å redigere det.</p>';return}transform.attach(root);transform.setMode('translate');const u=root.userData;card.innerHTML=`<span class="kicker">${u.brand}</span><h3>${u.name}</h3><p>Bruk pilene i 3D-rommet eller kontrollene her.</p><div class="meta"><div><small>Bredde</small><b>${Math.round(u.w*1000)} mm</b></div><div><small>Dybde</small><b>${Math.round(u.d*1000)} mm</b></div></div><div class="actions"><button id="move">Flytt</button><button id="rotate">Roter</button><button id="left">← 10 cm</button><button id="right">10 cm →</button><button id="remove" class="danger">Fjern</button><button id="duplicate">Dupliser</button></div>`;document.getElementById('move').onclick=()=>transform.setMode('translate');document.getElementById('rotate').onclick=()=>transform.setMode('rotate');document.getElementById('left').onclick=()=>{root.position.x-=.1;clampSelected()};document.getElementById('right').onclick=()=>{root.position.x+=.1;clampSelected()};document.getElementById('remove').onclick=()=>{transform.detach();scene.remove(root);const i=selectable.indexOf(root);if(i>-1)selectable.splice(i,1);select(null)};document.getElementById('duplicate').onclick=()=>{const clone=root.clone();clone.position.copy(root.position);clone.position.x+=.35;clone.userData={...root.userData};clone.traverse(o=>{if(o.isMesh)o.userData.root=clone});scene.add(clone);selectable.push(clone);select(clone);clampSelected()}}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();renderer.domElement.addEventListener('pointerup',e=>{if(transform.dragging)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1);ray.setFromCamera(pointer,camera);const meshes=[];selectable.forEach(s=>s.traverse(o=>{if(o.isMesh)meshes.push(o)}));const hit=ray.intersectObjects(meshes,false)[0];if(hit)select(hit.object.userData.root)});
const floorColors={stone:0xb7b4aa,sand:0xd8c9ad,dark:0x555b5b,marble:0xe9e8e2},wallColors={white:0xeeeae1,greige:0xc9c1b2,sage:0x9fa99d,slate:0x667173};document.querySelectorAll('[data-floor]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-floor]').forEach(x=>x.classList.remove('active'));b.classList.add('active');mats.floor.color.setHex(floorColors[b.dataset.floor])}));document.querySelectorAll('[data-wall]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-wall]').forEach(x=>x.classList.remove('active'));b.classList.add('active');mats.wall.color.setHex(wallColors[b.dataset.wall])}));
document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.add,makers={toilet,vanity,shower,tub,cabinet,plant};const o=makers[t](0,.35);select(o)}));
function setMode(next){mode=next;document.querySelectorAll('.toolbar .tool').forEach(x=>x.classList.remove('active'));controls.enabled=true;if(next==='orbit'){camera.position.set(4.3,3.05,4.8);controls.target.set(0,1.05,0);controls.enablePan=true;document.getElementById('orbitBtn').classList.add('active')}if(next==='walk'){camera.position.set(0,1.62,1.02);controls.target.set(0,1.42,-1.05);controls.enablePan=false;document.getElementById('walkBtn').classList.add('active')}if(next==='top'){camera.position.set(0,6,.01);controls.target.set(0,0,0);controls.enablePan=true;document.getElementById('topBtn').classList.add('active')}controls.update()}
document.getElementById('orbitBtn').addEventListener('click',()=>setMode('orbit'));document.getElementById('walkBtn').addEventListener('click',()=>setMode('walk'));document.getElementById('topBtn').addEventListener('click',()=>setMode('top'));document.getElementById('resetBtn').addEventListener('click',()=>setMode(mode));
grid=new THREE.GridHelper(3,30,0x1769d1,0x9eb0bd);grid.position.y=.012;grid.visible=false;scene.add(grid);document.getElementById('gridToggle').addEventListener('change',e=>grid.visible=e.target.checked);
const dims=new THREE.Group();const lineMat=new THREE.LineBasicMaterial({color:0x1769d1});function line(a,b){return new THREE.Line(new THREE.BufferGeometry().setFromPoints([a,b]),lineMat)}dims.add(line(new THREE.Vector3(-1.5,.03,1.34),new THREE.Vector3(1.5,.03,1.34)),line(new THREE.Vector3(1.64,.03,-1.2),new THREE.Vector3(1.64,.03,1.2)));scene.add(dims);document.getElementById('measureToggle').addEventListener('change',e=>dims.visible=e.target.checked);
function resize(){const w=Math.max(stage.clientWidth,320),h=Math.max(canvas.clientHeight||700,360);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();if(loader)loader.style.display='none';renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});