import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.167.1/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.167.1/examples/jsm/controls/OrbitControls.js';
import {TransformControls} from 'https://cdn.jsdelivr.net/npm/three@0.167.1/examples/jsm/controls/TransformControls.js';
const canvas=document.getElementById('room'),stage=document.getElementById('stage'),card=document.getElementById('objectCard');
const scene=new THREE.Scene();scene.background=new THREE.Color(0xdfe7eb);
const camera=new THREE.PerspectiveCamera(48,1,.05,100);camera.position.set(4.5,3.2,5.3);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.1,0);controls.enableDamping=true;controls.minDistance=2;controls.maxDistance=9;controls.maxPolarAngle=Math.PI/2.02;
const transform=new TransformControls(camera,renderer.domElement);scene.add(transform);transform.addEventListener('dragging-changed',e=>controls.enabled=!e.value);transform.setTranslationSnap(.05);
scene.add(new THREE.HemisphereLight(0xffffff,0x53636a,2.4));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(2.5,5,3);sun.castShadow=true;scene.add(sun);
const room={w:3,d:2.4,h:2.5};let selected=null,grid=null,mode='orbit';const selectable=[];
const mats={floor:new THREE.MeshStandardMaterial({color:0xb7b4aa,roughness:.7}),wall:new THREE.MeshStandardMaterial({color:0xeeeae1,roughness:.8}),white:new THREE.MeshStandardMaterial({color:0xf7f7f5,roughness:.35}),ceramic:new THREE.MeshStandardMaterial({color:0xfafafa,roughness:.22}),chrome:new THREE.MeshStandardMaterial({color:0xb9c2c5,metalness:.85,roughness:.18}),wood:new THREE.MeshStandardMaterial({color:0x9a7150,roughness:.55}),glass:new THREE.MeshPhysicalMaterial({color:0xcfe7ea,transparent:true,opacity:.25,roughness:.05,metalness:0,side:THREE.DoubleSide}),dark:new THREE.MeshStandardMaterial({color:0x263238,roughness:.4}),green:new THREE.MeshStandardMaterial({color:0x56745e,roughness:.8})};
function box(w,h,d,mat,x,y,z){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;scene.add(m);return m}
const floor=box(room.w,.08,room.d,mats.floor,0,-.04,0),back=box(room.w,room.h,.08,mats.wall,0,room.h/2,-room.d/2),left=box(.08,room.h,room.d,mats.wall,-room.w/2,room.h/2,0);
function grout(){const g=new THREE.Group();const lm=new THREE.LineBasicMaterial({color:0x8d928e,transparent:true,opacity:.28});for(let x=-1.5;x<=1.5;x+=.6){const geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(x,.005,-1.2),new THREE.Vector3(x,.005,1.2)]);g.add(new THREE.Line(geo,lm))}for(let z=-1.2;z<=1.2;z+=.6){const geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-1.5,.006,z),new THREE.Vector3(1.5,.006,z)]);g.add(new THREE.Line(geo,lm))}scene.add(g)}grout();
function tag(root,type,name,brand,w,d){root.userData={type,name,brand,w,d};root.traverse(o=>{if(o.isMesh){o.userData.root=root;o.castShadow=true;o.receiveShadow=true}});selectable.push(root);return root}
function toilet(x,z){const g=new THREE.Group();const base=new THREE.Mesh(new THREE.CylinderGeometry(.24,.3,.42,32),mats.ceramic);base.scale.z=.8;base.position.y=.24;g.add(base);const bowl=new THREE.Mesh(new THREE.TorusGeometry(.27,.075,16,32),mats.ceramic);bowl.rotation.x=Math.PI/2;bowl.position.set(0,.5,.02);g.add(bowl);const tank=new THREE.Mesh(new THREE.BoxGeometry(.48,.48,.2),mats.ceramic);tank.position.set(0,.55,-.25);g.add(tank);g.position.set(x,0,z);scene.add(g);return tag(g,'toilet','Vegghengt WC','Geberit · demo',.55,.7)}
function vanity(x,z){const g=new THREE.Group();const cab=new THREE.Mesh(new THREE.BoxGeometry(1,.55,.48),mats.wood);cab.position.y=.52;g.add(cab);const top=new THREE.Mesh(new THREE.BoxGeometry(1.04,.08,.52),mats.white);top.position.y=.83;g.add(top);const basin=new THREE.Mesh(new THREE.CylinderGeometry(.2,.17,.09,32),mats.ceramic);basin.scale.z=1.5;basin.position.set(0,.88,0);g.add(basin);const tap=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,.25,12),mats.chrome);tap.position.set(.2,1.02,-.12);g.add(tap);const mirror=new THREE.Mesh(new THREE.CircleGeometry(.38,32),new THREE.MeshStandardMaterial({color:0x9fc0c8,metalness:.35,roughness:.08}));mirror.position.set(0,1.55,-.25);mirror.rotation.y=0;g.add(mirror);g.position.set(x,0,z);scene.add(g);return tag(g,'vanity','Servantmøbel 100','Dansani · demo',1.04,.52)}
function shower(x,z){const g=new THREE.Group();const tray=new THREE.Mesh(new THREE.BoxGeometry(1,.05,1),mats.white);tray.position.y=.025;g.add(tray);const a=new THREE.Mesh(new THREE.PlaneGeometry(1,2.05),mats.glass);a.position.set(0,1.03,-.5);g.add(a);const b=new THREE.Mesh(new THREE.PlaneGeometry(1,2.05),mats.glass);b.rotation.y=Math.PI/2;b.position.set(-.5,1.03,0);g.add(b);const pipe=new THREE.Mesh(new THREE.CylinderGeometry(.018,.018,1.8,12),mats.chrome);pipe.position.set(.34,1.05,-.43);g.add(pipe);const head=new THREE.Mesh(new THREE.CylinderGeometry(.14,.14,.025,24),mats.chrome);head.rotation.x=Math.PI/2;head.position.set(.34,1.92,-.34);g.add(head);g.position.set(x,0,z);scene.add(g);return tag(g,'shower','Dusjhjørne 100×100','INR / Hansgrohe · demo',1,1)}
function tub(x,z){const g=new THREE.Group();const outer=new THREE.Mesh(new THREE.BoxGeometry(1.65,.58,.75),mats.ceramic);outer.position.y=.31;g.add(outer);const inner=new THREE.Mesh(new THREE.BoxGeometry(1.38,.18,.52),new THREE.MeshStandardMaterial({color:0xc7dce2}));inner.position.y=.54;g.add(inner);g.position.set(x,0,z);scene.add(g);return tag(g,'tub','Frittstående badekar','VikingBad · demo',1.65,.75)}
function cabinet(x,z){const g=new THREE.Group();const c=new THREE.Mesh(new THREE.BoxGeometry(.45,1.75,.4),mats.wood);c.position.y=.875;g.add(c);g.position.set(x,0,z);scene.add(g);return tag(g,'cabinet','Høyskap','Fossbad · demo',.45,.4)}
function plant(x,z){const g=new THREE.Group();const pot=new THREE.Mesh(new THREE.CylinderGeometry(.18,.13,.32,20),mats.dark);pot.position.y=.16;g.add(pot);for(let i=0;i<7;i++){const leaf=new THREE.Mesh(new THREE.SphereGeometry(.13,12,8),mats.green);leaf.scale.set(.55,1.8,.45);leaf.position.set(Math.sin(i)*.12,.45+(i%3)*.1,Math.cos(i)*.1);leaf.rotation.z=(i-3)*.25;g.add(leaf)}g.position.set(x,0,z);scene.add(g);return tag(g,'plant','Dekorplante','Showroom',.4,.4)}
toilet(-.72,-.82);vanity(.62,-.91);shower(1,.58);cabinet(-1.18,.35);
function select(root){selected=root;transform.detach();if(!root){card.innerHTML='<h3>Velg noe i rommet</h3><p>Trykk på et produkt. Deretter kan du flytte, rotere eller fjerne det.</p>';return}transform.attach(root);transform.setMode('translate');const u=root.userData;card.innerHTML=`<span class="kicker">${u.brand}</span><h3>${u.name}</h3><p>Flytt objektet direkte i rommet med pilene, eller bruk knappene under.</p><div class="meta"><div><small>Bredde</small><b>${Math.round(u.w*1000)} mm</b></div><div><small>Dybde</small><b>${Math.round(u.d*1000)} mm</b></div></div><div class="actions"><button id="move">Flytt</button><button id="rotate">Roter</button><button id="left">← 10 cm</button><button id="right">10 cm →</button><button id="remove" class="danger">Fjern</button><button id="duplicate">Dupliser</button></div>`;document.getElementById('move').onclick=()=>transform.setMode('translate');document.getElementById('rotate').onclick=()=>transform.setMode('rotate');document.getElementById('left').onclick=()=>{root.position.x=Math.max(-1.25,root.position.x-.1)};document.getElementById('right').onclick=()=>{root.position.x=Math.min(1.25,root.position.x+.1)};document.getElementById('remove').onclick=()=>{transform.detach();scene.remove(root);selectable.splice(selectable.indexOf(root),1);select(null)};document.getElementById('duplicate').onclick=()=>{const clone=root.clone();clone.position.x=Math.min(1.1,root.position.x+.35);clone.userData={...root.userData};clone.traverse(o=>{if(o.isMesh)o.userData.root=clone});scene.add(clone);selectable.push(clone);select(clone)}}
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();renderer.domElement.addEventListener('pointerdown',e=>{if(transform.dragging)return;const r=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,camera);const meshes=[];selectable.forEach(s=>s.traverse(o=>{if(o.isMesh)meshes.push(o)}));const hit=ray.intersectObjects(meshes,false)[0];if(hit)select(hit.object.userData.root)});
document.querySelectorAll('[data-floor]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-floor]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const colors={stone:0xb7b4aa,sand:0xd8c9ad,dark:0x555b5b,marble:0xe9e8e2};mats.floor.color.setHex(colors[b.dataset.floor])});document.querySelectorAll('[data-wall]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-wall]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const colors={white:0xeeeae1,greige:0xc9c1b2,sage:0x9fa99d,slate:0x667173};mats.wall.color.setHex(colors[b.dataset.wall])});
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const t=b.dataset.add;let o;if(t==='toilet')o=toilet(0,.35);if(t==='vanity')o=vanity(0,.3);if(t==='shower')o=shower(.7,.4);if(t==='tub')o=tub(0,.35);if(t==='cabinet')o=cabinet(0,.3);if(t==='plant')o=plant(0,.3);select(o)});
function setMode(next){mode=next;document.querySelectorAll('.toolbar .tool').forEach(x=>x.classList.remove('active'));if(next==='orbit'){camera.position.set(4.5,3.2,5.3);controls.target.set(0,1.1,0);controls.enablePan=true;document.getElementById('orbitBtn').classList.add('active')}if(next==='walk'){camera.position.set(0,1.62,1.05);controls.target.set(0,1.45,-1);controls.enablePan=false;document.getElementById('walkBtn').classList.add('active')}if(next==='top'){camera.position.set(0,6,.01);controls.target.set(0,0,0);controls.enablePan=true;document.getElementById('topBtn').classList.add('active')}controls.update()}
document.getElementById('orbitBtn').onclick=()=>setMode('orbit');document.getElementById('walkBtn').onclick=()=>setMode('walk');document.getElementById('topBtn').onclick=()=>setMode('top');document.getElementById('resetBtn').onclick=()=>setMode(mode);
function makeGrid(){grid=new THREE.GridHelper(3,30,0x1769d1,0x9eb0bd);grid.position.y=.012;grid.visible=false;scene.add(grid)}makeGrid();document.getElementById('gridToggle').onchange=e=>grid.visible=e.target.checked;
const dims=new THREE.Group();function line(a,b){const g=new THREE.BufferGeometry().setFromPoints([a,b]);return new THREE.Line(g,new THREE.LineBasicMaterial({color:0x1769d1}))}dims.add(line(new THREE.Vector3(-1.5,.03,1.34),new THREE.Vector3(1.5,.03,1.34)));dims.add(line(new THREE.Vector3(1.64,.03,-1.2),new THREE.Vector3(1.64,.03,1.2)));scene.add(dims);document.getElementById('measureToggle').onchange=e=>dims.visible=e.target.checked;
function resize(){const r=stage.getBoundingClientRect();const h=canvas.clientHeight||760;renderer.setSize(r.width,h,false);camera.aspect=r.width/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(stage);resize();renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});